### ISSUE TITLE
Did not work!

### ISSUE THREAD

**Issue by SetimoCristian** [YezerSTN/GrowBot#1]
Did not work!
![Captura de tela 2023-12-04 143637](https://github.com/YezerSTN/GrowBot/assets/106691503/96ce6ac6-3526-469b-9c3c-17245c3c8dea)

Uploaded your updates, but it didn't work, the billing screen is still active.
Could you please update the error, I really appreciate it!

**Comment by YezerSTN** [comment]
![image](https://github.com/YezerSTN/GrowBot/assets/109930585/688ec39d-b3b2-4ef9-97fc-190399cb9585)
sorry, I uploaded the wrong extension, but I updated the repository.

**Comment by KingS4D** [comment]
Thanks bro, this is a big help
