### ISSUE TITLE
Growbot error 403

### ISSUE THREAD

**Issue by pamelasoaresdemoura** [YezerSTN/GrowBot#3]
Hello, I'm Brazilian so excuse my English... The Growbot extension already has the v2.0.7 update, according to some people the 403 error is due to an update from Instagram itself, but Growbot has already fixed this error in the 2.0.7 update Create an extension like this, but with the current version of Growbot, which is v2.0.7!!! As soon as you do this I will come here to download and test it and leave my feedback. Thanks in advance.

**Comment by YezerSTN** [comment]
Obrigado por me informar sobre a nova atualização, e eu a enviarei para todos em breve.

**Comment by pamelasoaresdemoura** [comment]
Obrigado, por favor nos envie sim... essa extensão é otima e facilita muito. Devo aguardar até semana que vem será?

**Comment by YezerSTN** [comment]
A nova versão 2.0.9 foi lançada :)

**Comment by SetimoCristian** [comment]
VOCÊ É FODASTICO!!!!! OBRIGADO
