### ISSUE TITLE
GrowBot Asks For Subscription

### ISSUE THREAD

**Issue by joyetan** [YezerSTN/GrowBot#4]
![capture-20231215-003737](https://github.com/YezerSTN/GrowBot/assets/153467314/41ff058d-2ac7-4355-8b84-53fdbff3a753)

So yea, I got this when I opened the extension. Thanks in advance for helping out with this issue!

**Comment by YezerSTN** [comment]
Try the new version 2.0.9 of GrowBot.
I solved that problem :)
